version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    container_name: apod_api
    restart: always
    links:
      - "db:database"
    env_file:
      - ../.env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage

  db:
    image: postgres:16-alpine
    container_name: apod_db_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
